### ISSUE TITLE
section on 'why'

### ISSUE THREAD

**Issue by gonsie** [Heatherms27/BlogPost#2]
After the assumptions section and before the implementation section, I think there should be a few paragraphs about *why* this equation is 'hello world'. Something along the lines of:
- PDEs are very common in math / computational math (Laplace is a PDE, right? 😬)
- solving these sorts of equations with a discretized form is very common and allows parallel awesomeness
- these sorts of operations are implemented either directly into a programming language or by a library, so looking at various code-ups helps users get a flavor for using a particular technology.

**Comment by Heatherms27** [comment]
Should it be after or before the assumptions section? I'm probably over-thinking, but the assumptions are there so the equation is easier to discretize to something that can be coded, so it may be better to say why it's a good idea to for people to learn how to code it before saying how to put it into a codable format.

**Comment by Heatherms27** [comment]
"The Heat Equation: High-Performance Scientific Computing Case Study":
https://www.computer.org/csdl/magazine/cs/2018/05/mcs2018050114/13rRUxC0SLx
